content-auditor-backend/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :registrations, only: [:create]
      delete :logout, to: "sessions#logout"
      get :logged_in, to: "sessions#logged_in"
      resources :documents
      resources :users
      resources :organizations
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

content-auditor-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

content-auditor-backend/app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
end

content-auditor-backend/app/models/organization.rb
class Organization < ApplicationRecord
    has_many :users
    has_many :documents, through: :users
end

content-auditor-backend/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email 
    validates_uniqueness_of :email
    belongs_to :organization
    has_many :documents

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

content-auditor-backend/app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController
    def index
        render json: Document.all 
    end

    def show
        render json: Document.find(params[:id])
    end

    def edit
        Document.find(params[:id]) 
    end

    def create
        document = Document.create!(
            content: params["document"]["content"], 
            hashedmessage: params["document"]["hashedmessage"], 
            user_id: params["document"]["user_id"]
        )
        if document
            render json: { status: 200 }
        else
            render json: { status: 500 }
        end
    end

    def update
        document = Document.find(params[:id])
        document.update(
            content: params["document"]["content"], 
            hashedmessage: params["document"]["hashedmessage"], 
            user_id: params["document"]["user_id"])
        if document
            render json: { status: 200 }
        else
            render json: { status: 500 }
        end
    end 

    def destroy
        document = Document.find(params[:id])
        document.destroy
    end

    # private 

    # def document_params
    #     params.require(:document).permit(:content, :hashedmessage, :user_id)
    # end
end

content-auditor-backend/app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < ApplicationController
    def index
        render json: Organization.all 
    end

    def show
        render json: Organization.find(params[:id])
    end

    def create
        organization = Organization.new(
            name: params["name"])
        if organization.save
            render json: { status: 200 }
        else
            render json: { message: "Organization not created" }
        end
    end

    def update
        organization = Organization.find(params[:id])
        organization.update(
            name: params["name"])
    end 

    def destroy
        organization = Organization.find(params[:id])
        organization.destroy
    end

    # private 

    # def organization_params
    #     params.require(:organization).permit(:name)
    # end
end

content-auditor-backend/app/controllers/api/v1/registrations_controller.rb
class Api::V1::RegistrationsController < ApplicationController
    def create
        #Need to add name, address, etc to registration create method
        user = User.create!(
            name: params['user']['name'],
            email: params['user']['email'],
            password: params['user']['password'],
            password_confirmation: params['user']['password_confirmation'],
            admin: params['user']['admin'],
            organization_id: params['user']['organization_id']
        )
        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                user: user
            }
        else
            render json: { status: 500 }
        end
    end
end

content-auditor-backend/app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < ApplicationController
    include CurrentUserConcern
    def create
        user = User
        .find_by(email: params["user"]["email"])
        .try(:authenticate, params["user"]["password"])
        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                logged_in: true,
                user: user
            }
        else
            render json: {status: 401 }
        end
    end

    def logged_in
        #exclude created at and DB ID
        if @current_user
            render json: {
                logged_in: true,
                user: @current_user,
                organization: @current_user.organization,
                documents: @current_user.documents
            }
        else
            render json: {
                logged_in: false,
                message: "Not logged in"
            }
        end
    end
    

    def logout
        reset_session
        render json: { status: 200, logged_out: true }
    end
end

content-auditor-backend/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    
    def index
        render json: User.all
    end

    def show
        render json: User.find(params[:id])
    end

    def create
        user = User.new(user_params)
        if user.save
            render json: { status: 200 }
        else
            render json: { message: "User not created"}
        end
    end

    def update
        user = User.find(params[:id])
        user.update(user_params)
    end 

    def destroy
        user = User.find(params[:id])
        user.destroy
    end

    private 

    def user_params
        params.require(:user).permit(:name, :email, :password_digest, :address, :admin, :organization_id)
    end
end

content-auditor-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

content-auditor-backend/app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern 
    extend ActiveSupport::Concern

    included do
        before_action :set_current_user
    end

    def set_current_user
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
    end
end

content-auditor-backend/app/helpers/api/v1/organizations_helper.rb
module Api::V1::OrganizationsHelper
end

content-auditor-backend/app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

content-auditor-backend/app/helpers/application_helper.rb
module ApplicationHelper
end

content-auditor-backend/app/helpers/documents_helper.rb
module DocumentsHelper
end

content-auditor-backend/app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :hashedmessages %>
    <%= form.text_field :hashedmessages %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

content-auditor-backend/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

content-auditor-backend/app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Address</th>
      <th>Hashedmessages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.content %></td>
        <td><%= document.address %></td>
        <td><%= document.hashedmessages %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

content-auditor-backend/app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

content-auditor-backend/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<p>
  <strong>Address:</strong>
  <%= @document.address %>
</p>

<p>
  <strong>Hashedmessages:</strong>
  <%= @document.hashedmessages %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

content-auditor-backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProvenanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>